"""Load FBref-style public player data with an offline sample fallback.

The project is intentionally honest about its data layer: the screening model is
designed around public, aggregated player statistics. Users can replace the
sample file with FBref-exported or Stathead-style midfield data using the same
column names.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import AS_OF_DATE, RAW_DIR, SAMPLE_FBREF_PATH


PLAYER_CONTEXT_MAY_2026 = {
    "Casemiro": {
        "date_of_birth": "1992-02-23",
        "squad": "Manchester United",
        "league": "Premier League",
        "is_target_candidate": False,
        "context_source": "Manchester United reference profile",
        "context_source_url": "https://www.manutd.com/",
        "availability_note": "Current United reference profile, not a target",
    },
    "Manuel Ugarte": {
        "date_of_birth": "2001-04-11",
        "squad": "Manchester United",
        "league": "Premier League",
        "is_target_candidate": False,
        "context_source": "Manchester United confirmed signing from PSG in Aug 2024",
        "context_source_url": "https://www.manutd.com/en/news/detail/transfer-news-manuel-ugarte-signs-from-psg",
        "availability_note": "Current United midfielder as of May 2026, not a target",
    },
    "Carlos Baleba": {
        "date_of_birth": "2004-01-03",
        "squad": "Brighton & Hove Albion",
        "league": "Premier League",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Carlos_Baleba",
    },
    "Ederson": {
        "date_of_birth": "1999-07-07",
        "squad": "Atalanta",
        "league": "Serie A",
        "context_source": "UEFA 2025/26 profile",
        "context_source_url": "https://www.uefa.com/uefachampionsleague/clubs/players/250188474--ederson/",
    },
    "Morten Hjulmand": {
        "date_of_birth": "1999-06-25",
        "squad": "Sporting CP",
        "league": "Primeira Liga",
        "context_source": "UEFA/Wikipedia profile checked May 2026",
        "context_source_url": "https://www.uefa.com/uefachampionsleague/clubs/players/250101557--morten-hjulmand/",
    },
    "João Gomes": {
        "date_of_birth": "2001-02-12",
        "squad": "Wolverhampton Wanderers",
        "league": "Premier League",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://www.premierleague.com/",
    },
    "Florentino Luís": {
        "date_of_birth": "1999-08-19",
        "squad": "Burnley",
        "league": "Premier League",
        "context_source": "UEFA 2025/26 profile lists Burnley loan",
        "context_source_url": "https://www.uefa.com/uefachampionsleague/clubs/players/250089225--florentino/",
        "availability_note": "EPL target pool: defensive specialist, on loan from Benfica in 2025/26 public profiles",
    },
    "Youssouf Fofana": {
        "date_of_birth": "1999-01-10",
        "squad": "AC Milan",
        "league": "Serie A",
        "context_source": "AC Milan / Transfermarkt profile checked May 2026",
        "context_source_url": "https://www.acmilan.com/en/news/articles/media/2024-08-17/official-statement-youssouf-fofana",
    },
    "Amadou Onana": {
        "date_of_birth": "2001-08-16",
        "squad": "Aston Villa",
        "league": "Premier League",
        "context_source": "Aston Villa transfer from Everton in Jul 2024",
        "context_source_url": "https://global.espn.com/football/story/_/id/40616656/aston-villa-complete-amadou-onana-transfer-everton",
    },
    "Elliot Anderson": {
        "date_of_birth": "2002-11-06",
        "squad": "Nottingham Forest",
        "league": "Premier League",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Elliot_Anderson_%28footballer%29",
    },
    "Bruno Guimarães": {
        "date_of_birth": "1997-11-16",
        "squad": "Newcastle United",
        "league": "Premier League",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Bruno_Guimar%C3%A3es",
    },
    "Johnny Cardoso": {
        "date_of_birth": "2001-09-20",
        "squad": "Atletico Madrid",
        "league": "La Liga",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Johnny_Cardoso",
    },
    "Adam Wharton": {
        "date_of_birth": "2004-02-06",
        "squad": "Crystal Palace",
        "league": "Premier League",
        "context_source": "UEFA/Wikipedia profile checked May 2026",
        "context_source_url": "https://www.uefa.com/uefaconferenceleague/clubs/players/250178736--adam-wharton/",
    },
    "Angelo Stiller": {
        "date_of_birth": "2001-04-04",
        "squad": "Stuttgart",
        "league": "Bundesliga",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Angelo_Stiller",
    },
    "Samuele Ricci": {
        "date_of_birth": "2001-08-21",
        "squad": "AC Milan",
        "league": "Serie A",
        "context_source": "AC Milan confirmed signing from Torino in Jul 2025",
        "context_source_url": "https://www.acmilan.com/en/news/articles/media/2025-07-03/official-statement-samuele-ricci",
    },
    "Alan Varela": {
        "date_of_birth": "2001-07-04",
        "squad": "Porto",
        "league": "Primeira Liga",
        "context_source": "UEFA/Wikipedia profile checked May 2026",
        "context_source_url": "https://www.uefa.com/uefaeuropaleague/clubs/players/250188256--alan-varela/",
    },
    "Exequiel Palacios": {
        "date_of_birth": "1998-10-05",
        "squad": "Bayer Leverkusen",
        "league": "Bundesliga",
        "context_source": "Bundesliga/Transfermarkt profile checked May 2026",
        "context_source_url": "https://www.bundesliga.com/en/bundesliga/player/exequiel-palacios/",
    },
    "Mats Wieffer": {
        "date_of_birth": "1999-11-16",
        "squad": "Brighton & Hove Albion",
        "league": "Premier League",
        "context_source": "Public profile checked May 2026",
        "context_source_url": "https://en.wikipedia.org/wiki/Mats_Wieffer",
    },
    "Hugo Larsson": {
        "date_of_birth": "2004-06-27",
        "squad": "Eintracht Frankfurt",
        "league": "Bundesliga",
        "context_source": "Eintracht/UEFA profile checked May 2026",
        "context_source_url": "https://en.eintracht.de/2024-2025/squad/hugo-larsson/",
    },
    "Aleix Garcia": {
        "date_of_birth": "1997-06-28",
        "squad": "Bayer Leverkusen",
        "league": "Bundesliga",
        "context_source": "Bundesliga confirmed Leverkusen signing in Jun 2024",
        "context_source_url": "https://www.bundesliga.com/en/bundesliga/news/bayer-leverkusen-sign-aleix-garcia-from-girona-27812",
    },
}


SAMPLE_PLAYERS = [
    {
        "player": "Casemiro",
        "squad": "Manchester United",
        "league": "Premier League",
        "age": 32,
        "is_target_candidate": False,
        "minutes": 2071,
        "market_value_m_eur": 20,
        "availability_note": "Current United reference profile, not a target",
        "tackles_interceptions": 122,
        "dribblers_tackled_pct": 48.5,
        "interceptions": 45,
        "blocks": 38,
        "aerial_win_pct": 63.2,
        "def_mid_third_actions": 166,
        "ball_recoveries": 176,
        "pressure_regains": 25,
        "fouls_committed": 55,
        "cards": 9,
        "miscontrols": 37,
        "dispossessed": 31,
        "defensive_actions_after_loss": 31,
        "pass_completion_pct": 82.1,
        "short_medium_pass_completion_pct": 88.4,
        "passes_received": 1008,
        "touches": 1506,
        "progressive_passes": 128,
        "progressive_carries": 21,
        "passes_into_final_third": 91,
        "carries_into_final_third": 10,
        "progressive_passing_distance": 5580,
        "live_ball_sca": 31,
    },
    {
        "player": "Carlos Baleba",
        "squad": "Brighton & Hove Albion",
        "league": "Premier League",
        "age": 22,
        "is_target_candidate": True,
        "minutes": 2580,
        "market_value_m_eur": 55,
        "availability_note": "May 2026 EPL target pool: young ball-winner with carrying upside",
        "tackles_interceptions": 124,
        "dribblers_tackled_pct": 57.8,
        "interceptions": 56,
        "blocks": 42,
        "aerial_win_pct": 55.0,
        "def_mid_third_actions": 190,
        "ball_recoveries": 252,
        "pressure_regains": 52,
        "fouls_committed": 45,
        "cards": 8,
        "miscontrols": 43,
        "dispossessed": 36,
        "defensive_actions_after_loss": 56,
        "pass_completion_pct": 84.2,
        "short_medium_pass_completion_pct": 89.5,
        "passes_received": 1420,
        "touches": 1990,
        "progressive_passes": 150,
        "progressive_carries": 82,
        "passes_into_final_third": 112,
        "carries_into_final_third": 48,
        "progressive_passing_distance": 6100,
        "live_ball_sca": 54,
    },
    {
        "player": "Ederson",
        "squad": "Atalanta",
        "league": "Serie A",
        "age": 24,
        "is_target_candidate": True,
        "minutes": 2822,
        "market_value_m_eur": 35,
        "availability_note": "Two-way transition defender",
        "tackles_interceptions": 166,
        "dribblers_tackled_pct": 54.1,
        "interceptions": 67,
        "blocks": 46,
        "aerial_win_pct": 58.4,
        "def_mid_third_actions": 216,
        "ball_recoveries": 268,
        "pressure_regains": 50,
        "fouls_committed": 47,
        "cards": 7,
        "miscontrols": 39,
        "dispossessed": 29,
        "defensive_actions_after_loss": 52,
        "pass_completion_pct": 82.9,
        "short_medium_pass_completion_pct": 88.7,
        "passes_received": 1428,
        "touches": 1994,
        "progressive_passes": 171,
        "progressive_carries": 64,
        "passes_into_final_third": 121,
        "carries_into_final_third": 38,
        "progressive_passing_distance": 6840,
        "live_ball_sca": 58,
    },
    {
        "player": "Morten Hjulmand",
        "squad": "Sporting CP",
        "league": "Primeira Liga",
        "age": 25,
        "is_target_candidate": True,
        "minutes": 2520,
        "market_value_m_eur": 35,
        "availability_note": "Aggressive holder with passing range",
        "tackles_interceptions": 154,
        "dribblers_tackled_pct": 52.6,
        "interceptions": 66,
        "blocks": 41,
        "aerial_win_pct": 57.1,
        "def_mid_third_actions": 205,
        "ball_recoveries": 250,
        "pressure_regains": 46,
        "fouls_committed": 58,
        "cards": 11,
        "miscontrols": 28,
        "dispossessed": 23,
        "defensive_actions_after_loss": 48,
        "pass_completion_pct": 85.2,
        "short_medium_pass_completion_pct": 90.6,
        "passes_received": 1510,
        "touches": 2042,
        "progressive_passes": 188,
        "progressive_carries": 42,
        "passes_into_final_third": 148,
        "carries_into_final_third": 25,
        "progressive_passing_distance": 7480,
        "live_ball_sca": 49,
    },
    {
        "player": "João Gomes",
        "squad": "Wolverhampton Wanderers",
        "league": "Premier League",
        "age": 23,
        "is_target_candidate": True,
        "minutes": 2464,
        "market_value_m_eur": 40,
        "availability_note": "Ball-winning transition disruptor",
        "tackles_interceptions": 189,
        "dribblers_tackled_pct": 55.4,
        "interceptions": 63,
        "blocks": 48,
        "aerial_win_pct": 50.6,
        "def_mid_third_actions": 227,
        "ball_recoveries": 261,
        "pressure_regains": 58,
        "fouls_committed": 64,
        "cards": 11,
        "miscontrols": 46,
        "dispossessed": 43,
        "defensive_actions_after_loss": 61,
        "pass_completion_pct": 81.7,
        "short_medium_pass_completion_pct": 87.3,
        "passes_received": 1168,
        "touches": 1726,
        "progressive_passes": 115,
        "progressive_carries": 52,
        "passes_into_final_third": 84,
        "carries_into_final_third": 29,
        "progressive_passing_distance": 5090,
        "live_ball_sca": 54,
    },
    {
        "player": "Manuel Ugarte",
        "squad": "Manchester United",
        "league": "Premier League",
        "age": 25,
        "is_target_candidate": False,
        "minutes": 1774,
        "market_value_m_eur": 45,
        "availability_note": "Current United midfielder as of May 2026, not a target",
        "tackles_interceptions": 151,
        "dribblers_tackled_pct": 59.6,
        "interceptions": 53,
        "blocks": 30,
        "aerial_win_pct": 52.4,
        "def_mid_third_actions": 184,
        "ball_recoveries": 204,
        "pressure_regains": 48,
        "fouls_committed": 49,
        "cards": 10,
        "miscontrols": 20,
        "dispossessed": 24,
        "defensive_actions_after_loss": 55,
        "pass_completion_pct": 91.0,
        "short_medium_pass_completion_pct": 94.1,
        "passes_received": 1232,
        "touches": 1598,
        "progressive_passes": 91,
        "progressive_carries": 23,
        "passes_into_final_third": 65,
        "carries_into_final_third": 14,
        "progressive_passing_distance": 3530,
        "live_ball_sca": 23,
    },
    {
        "player": "Florentino Luís",
        "squad": "Benfica",
        "league": "Primeira Liga",
        "age": 24,
        "is_target_candidate": True,
        "minutes": 1745,
        "market_value_m_eur": 30,
        "availability_note": "Defensive specialist",
        "tackles_interceptions": 137,
        "dribblers_tackled_pct": 60.2,
        "interceptions": 55,
        "blocks": 36,
        "aerial_win_pct": 64.5,
        "def_mid_third_actions": 173,
        "ball_recoveries": 198,
        "pressure_regains": 41,
        "fouls_committed": 38,
        "cards": 6,
        "miscontrols": 24,
        "dispossessed": 22,
        "defensive_actions_after_loss": 44,
        "pass_completion_pct": 87.5,
        "short_medium_pass_completion_pct": 92.4,
        "passes_received": 996,
        "touches": 1397,
        "progressive_passes": 83,
        "progressive_carries": 18,
        "passes_into_final_third": 62,
        "carries_into_final_third": 9,
        "progressive_passing_distance": 3310,
        "live_ball_sca": 19,
    },
    {
        "player": "Youssouf Fofana",
        "squad": "AC Milan",
        "league": "Serie A",
        "age": 27,
        "is_target_candidate": True,
        "minutes": 2580,
        "market_value_m_eur": 30,
        "availability_note": "Serie A target pool: range, carries, and duels",
        "tackles_interceptions": 138,
        "dribblers_tackled_pct": 49.9,
        "interceptions": 49,
        "blocks": 42,
        "aerial_win_pct": 56.6,
        "def_mid_third_actions": 181,
        "ball_recoveries": 232,
        "pressure_regains": 43,
        "fouls_committed": 43,
        "cards": 7,
        "miscontrols": 42,
        "dispossessed": 39,
        "defensive_actions_after_loss": 47,
        "pass_completion_pct": 83.4,
        "short_medium_pass_completion_pct": 88.1,
        "passes_received": 1360,
        "touches": 1962,
        "progressive_passes": 177,
        "progressive_carries": 73,
        "passes_into_final_third": 136,
        "carries_into_final_third": 46,
        "progressive_passing_distance": 6900,
        "live_ball_sca": 62,
    },
    {
        "player": "Amadou Onana",
        "squad": "Aston Villa",
        "league": "Premier League",
        "age": 24,
        "is_target_candidate": True,
        "minutes": 2277,
        "market_value_m_eur": 50,
        "availability_note": "EPL target pool: physical defensive upside",
        "tackles_interceptions": 116,
        "dribblers_tackled_pct": 47.1,
        "interceptions": 48,
        "blocks": 49,
        "aerial_win_pct": 71.9,
        "def_mid_third_actions": 170,
        "ball_recoveries": 202,
        "pressure_regains": 30,
        "fouls_committed": 45,
        "cards": 7,
        "miscontrols": 38,
        "dispossessed": 34,
        "defensive_actions_after_loss": 34,
        "pass_completion_pct": 84.7,
        "short_medium_pass_completion_pct": 90.1,
        "passes_received": 1046,
        "touches": 1532,
        "progressive_passes": 113,
        "progressive_carries": 31,
        "passes_into_final_third": 85,
        "carries_into_final_third": 19,
        "progressive_passing_distance": 4540,
        "live_ball_sca": 28,
    },
    {
        "player": "Elliot Anderson",
        "squad": "Nottingham Forest",
        "league": "Premier League",
        "age": 23,
        "is_target_candidate": True,
        "minutes": 2880,
        "market_value_m_eur": 75,
        "availability_note": "May 2026 EPL target pool: high-cost controller, availability caveat",
        "tackles_interceptions": 156,
        "dribblers_tackled_pct": 52.8,
        "interceptions": 60,
        "blocks": 45,
        "aerial_win_pct": 54.2,
        "def_mid_third_actions": 205,
        "ball_recoveries": 270,
        "pressure_regains": 56,
        "fouls_committed": 48,
        "cards": 6,
        "miscontrols": 32,
        "dispossessed": 30,
        "defensive_actions_after_loss": 61,
        "pass_completion_pct": 86.4,
        "short_medium_pass_completion_pct": 91.1,
        "passes_received": 1900,
        "touches": 2520,
        "progressive_passes": 218,
        "progressive_carries": 91,
        "passes_into_final_third": 166,
        "carries_into_final_third": 56,
        "progressive_passing_distance": 8200,
        "live_ball_sca": 70,
    },
    {
        "player": "Bruno Guimarães",
        "squad": "Newcastle United",
        "league": "Premier League",
        "age": 26,
        "is_target_candidate": True,
        "minutes": 3059,
        "market_value_m_eur": 85,
        "availability_note": "Control creator, premium market",
        "tackles_interceptions": 174,
        "dribblers_tackled_pct": 50.5,
        "interceptions": 61,
        "blocks": 43,
        "aerial_win_pct": 48.7,
        "def_mid_third_actions": 205,
        "ball_recoveries": 272,
        "pressure_regains": 61,
        "fouls_committed": 66,
        "cards": 13,
        "miscontrols": 45,
        "dispossessed": 38,
        "defensive_actions_after_loss": 67,
        "pass_completion_pct": 84.8,
        "short_medium_pass_completion_pct": 90.2,
        "passes_received": 2150,
        "touches": 2798,
        "progressive_passes": 261,
        "progressive_carries": 86,
        "passes_into_final_third": 196,
        "carries_into_final_third": 49,
        "progressive_passing_distance": 9420,
        "live_ball_sca": 91,
    },
    {
        "player": "Johnny Cardoso",
        "squad": "Atletico Madrid",
        "league": "La Liga",
        "age": 24,
        "is_target_candidate": True,
        "minutes": 2050,
        "market_value_m_eur": 35,
        "availability_note": "La Liga target pool: defensive midfielder with ball-carrying balance",
        "tackles_interceptions": 138,
        "dribblers_tackled_pct": 54.8,
        "interceptions": 59,
        "blocks": 40,
        "aerial_win_pct": 58.7,
        "def_mid_third_actions": 184,
        "ball_recoveries": 215,
        "pressure_regains": 43,
        "fouls_committed": 37,
        "cards": 6,
        "miscontrols": 24,
        "dispossessed": 22,
        "defensive_actions_after_loss": 46,
        "pass_completion_pct": 87.8,
        "short_medium_pass_completion_pct": 92.6,
        "passes_received": 1395,
        "touches": 1810,
        "progressive_passes": 145,
        "progressive_carries": 49,
        "passes_into_final_third": 111,
        "carries_into_final_third": 29,
        "progressive_passing_distance": 5820,
        "live_ball_sca": 39,
    },
    {
        "player": "Adam Wharton",
        "squad": "Crystal Palace",
        "league": "Premier League",
        "age": 20,
        "is_target_candidate": True,
        "minutes": 1200,
        "market_value_m_eur": 35,
        "availability_note": "Young controller, sample-size caution",
        "tackles_interceptions": 72,
        "dribblers_tackled_pct": 54.7,
        "interceptions": 31,
        "blocks": 18,
        "aerial_win_pct": 48.2,
        "def_mid_third_actions": 85,
        "ball_recoveries": 104,
        "pressure_regains": 22,
        "fouls_committed": 18,
        "cards": 3,
        "miscontrols": 13,
        "dispossessed": 12,
        "defensive_actions_after_loss": 24,
        "pass_completion_pct": 85.9,
        "short_medium_pass_completion_pct": 91.0,
        "passes_received": 730,
        "touches": 955,
        "progressive_passes": 101,
        "progressive_carries": 24,
        "passes_into_final_third": 78,
        "carries_into_final_third": 13,
        "progressive_passing_distance": 3750,
        "live_ball_sca": 26,
    },
    {
        "player": "Angelo Stiller",
        "squad": "Stuttgart",
        "league": "Bundesliga",
        "age": 23,
        "is_target_candidate": True,
        "minutes": 2634,
        "market_value_m_eur": 30,
        "availability_note": "High-volume passer",
        "tackles_interceptions": 105,
        "dribblers_tackled_pct": 46.8,
        "interceptions": 44,
        "blocks": 32,
        "aerial_win_pct": 45.1,
        "def_mid_third_actions": 151,
        "ball_recoveries": 226,
        "pressure_regains": 34,
        "fouls_committed": 28,
        "cards": 4,
        "miscontrols": 26,
        "dispossessed": 18,
        "defensive_actions_after_loss": 36,
        "pass_completion_pct": 90.8,
        "short_medium_pass_completion_pct": 94.2,
        "passes_received": 2055,
        "touches": 2638,
        "progressive_passes": 251,
        "progressive_carries": 55,
        "passes_into_final_third": 203,
        "carries_into_final_third": 32,
        "progressive_passing_distance": 9140,
        "live_ball_sca": 61,
    },
    {
        "player": "Samuele Ricci",
        "squad": "AC Milan",
        "league": "Serie A",
        "age": 24,
        "is_target_candidate": True,
        "minutes": 2304,
        "market_value_m_eur": 28,
        "availability_note": "Serie A target pool: press-resistant possession profile",
        "tackles_interceptions": 116,
        "dribblers_tackled_pct": 51.6,
        "interceptions": 52,
        "blocks": 33,
        "aerial_win_pct": 47.9,
        "def_mid_third_actions": 161,
        "ball_recoveries": 210,
        "pressure_regains": 39,
        "fouls_committed": 35,
        "cards": 6,
        "miscontrols": 22,
        "dispossessed": 19,
        "defensive_actions_after_loss": 42,
        "pass_completion_pct": 87.2,
        "short_medium_pass_completion_pct": 92.0,
        "passes_received": 1412,
        "touches": 1831,
        "progressive_passes": 154,
        "progressive_carries": 38,
        "passes_into_final_third": 116,
        "carries_into_final_third": 21,
        "progressive_passing_distance": 6080,
        "live_ball_sca": 38,
    },
    {
        "player": "Alan Varela",
        "squad": "Porto",
        "league": "Primeira Liga",
        "age": 22,
        "is_target_candidate": True,
        "minutes": 2225,
        "market_value_m_eur": 30,
        "availability_note": "Balanced anchor, promising age curve",
        "tackles_interceptions": 126,
        "dribblers_tackled_pct": 53.9,
        "interceptions": 58,
        "blocks": 35,
        "aerial_win_pct": 52.1,
        "def_mid_third_actions": 169,
        "ball_recoveries": 220,
        "pressure_regains": 42,
        "fouls_committed": 41,
        "cards": 8,
        "miscontrols": 25,
        "dispossessed": 21,
        "defensive_actions_after_loss": 45,
        "pass_completion_pct": 86.1,
        "short_medium_pass_completion_pct": 91.4,
        "passes_received": 1330,
        "touches": 1762,
        "progressive_passes": 161,
        "progressive_carries": 35,
        "passes_into_final_third": 122,
        "carries_into_final_third": 20,
        "progressive_passing_distance": 6320,
        "live_ball_sca": 36,
    },
    {
        "player": "Exequiel Palacios",
        "squad": "Bayer Leverkusen",
        "league": "Bundesliga",
        "age": 25,
        "is_target_candidate": True,
        "minutes": 1986,
        "market_value_m_eur": 45,
        "availability_note": "Elite control, availability watch",
        "tackles_interceptions": 110,
        "dribblers_tackled_pct": 52.9,
        "interceptions": 43,
        "blocks": 30,
        "aerial_win_pct": 54.0,
        "def_mid_third_actions": 150,
        "ball_recoveries": 197,
        "pressure_regains": 38,
        "fouls_committed": 27,
        "cards": 5,
        "miscontrols": 16,
        "dispossessed": 15,
        "defensive_actions_after_loss": 40,
        "pass_completion_pct": 91.7,
        "short_medium_pass_completion_pct": 94.8,
        "passes_received": 1625,
        "touches": 2018,
        "progressive_passes": 177,
        "progressive_carries": 49,
        "passes_into_final_third": 146,
        "carries_into_final_third": 31,
        "progressive_passing_distance": 6810,
        "live_ball_sca": 48,
    },
    {
        "player": "Mats Wieffer",
        "squad": "Brighton & Hove Albion",
        "league": "Premier League",
        "age": 26,
        "is_target_candidate": True,
        "minutes": 2385,
        "market_value_m_eur": 32,
        "availability_note": "EPL target pool: tall distributor with defensive base",
        "tackles_interceptions": 130,
        "dribblers_tackled_pct": 51.2,
        "interceptions": 57,
        "blocks": 39,
        "aerial_win_pct": 66.1,
        "def_mid_third_actions": 176,
        "ball_recoveries": 231,
        "pressure_regains": 36,
        "fouls_committed": 37,
        "cards": 5,
        "miscontrols": 29,
        "dispossessed": 24,
        "defensive_actions_after_loss": 39,
        "pass_completion_pct": 86.5,
        "short_medium_pass_completion_pct": 91.2,
        "passes_received": 1505,
        "touches": 1997,
        "progressive_passes": 183,
        "progressive_carries": 44,
        "passes_into_final_third": 140,
        "carries_into_final_third": 25,
        "progressive_passing_distance": 7160,
        "live_ball_sca": 43,
    },
    {
        "player": "Hugo Larsson",
        "squad": "Eintracht Frankfurt",
        "league": "Bundesliga",
        "age": 21,
        "is_target_candidate": True,
        "minutes": 2380,
        "market_value_m_eur": 45,
        "availability_note": "Bundesliga target pool: young two-way controller",
        "tackles_interceptions": 128,
        "dribblers_tackled_pct": 51.6,
        "interceptions": 49,
        "blocks": 36,
        "aerial_win_pct": 56.2,
        "def_mid_third_actions": 169,
        "ball_recoveries": 224,
        "pressure_regains": 44,
        "fouls_committed": 36,
        "cards": 6,
        "miscontrols": 27,
        "dispossessed": 23,
        "defensive_actions_after_loss": 47,
        "pass_completion_pct": 86.6,
        "short_medium_pass_completion_pct": 91.8,
        "passes_received": 1510,
        "touches": 1985,
        "progressive_passes": 162,
        "progressive_carries": 58,
        "passes_into_final_third": 120,
        "carries_into_final_third": 34,
        "progressive_passing_distance": 6300,
        "live_ball_sca": 46,
    },
    {
        "player": "Aleix Garcia",
        "squad": "Bayer Leverkusen",
        "league": "Bundesliga",
        "age": 28,
        "is_target_candidate": True,
        "minutes": 3062,
        "market_value_m_eur": 25,
        "availability_note": "Bundesliga target pool: possession controller, lighter duelling profile",
        "tackles_interceptions": 123,
        "dribblers_tackled_pct": 44.9,
        "interceptions": 55,
        "blocks": 36,
        "aerial_win_pct": 42.5,
        "def_mid_third_actions": 164,
        "ball_recoveries": 260,
        "pressure_regains": 38,
        "fouls_committed": 39,
        "cards": 6,
        "miscontrols": 31,
        "dispossessed": 27,
        "defensive_actions_after_loss": 42,
        "pass_completion_pct": 89.7,
        "short_medium_pass_completion_pct": 93.6,
        "passes_received": 2300,
        "touches": 2972,
        "progressive_passes": 304,
        "progressive_carries": 64,
        "passes_into_final_third": 245,
        "carries_into_final_third": 36,
        "progressive_passing_distance": 11200,
        "live_ball_sca": 77,
    },
]


def write_sample_dataset(path: Path = SAMPLE_FBREF_PATH) -> Path:
    """Write the included public-data-style fallback sample to disk."""

    path.parent.mkdir(parents=True, exist_ok=True)
    sample = pd.DataFrame(SAMPLE_PLAYERS)
    sample = apply_may_2026_context(sample)
    sample.to_csv(path, index=False)
    return path


def load_fbref_player_stats(
    path: str | Path | None = None, use_sample: bool = True
) -> pd.DataFrame:
    """Load aggregated player stats.

    Parameters
    ----------
    path:
        Optional CSV path. If omitted, the project sample CSV is used.
    use_sample:
        When True, create and load the sample dataset if the CSV is missing.
    """

    data_path = Path(path) if path else SAMPLE_FBREF_PATH
    if not data_path.exists():
        if not use_sample:
            raise FileNotFoundError(f"No FBref-style data found at {data_path}")
        write_sample_dataset(data_path)

    df = pd.read_csv(data_path)
    return clean_fbref_player_stats(df)


def clean_fbref_player_stats(df: pd.DataFrame) -> pd.DataFrame:
    """Standardize column names and numeric types for scoring."""

    cleaned = apply_may_2026_context(df.copy())
    cleaned.columns = (
        cleaned.columns.str.strip()
        .str.lower()
        .str.replace("%", "pct", regex=False)
        .str.replace("/", "_", regex=False)
        .str.replace(" ", "_", regex=False)
    )

    text_cols = {
        "player",
        "squad",
        "league",
        "availability_note",
        "date_of_birth",
        "context_source",
        "context_source_url",
    }
    if "is_target_candidate" not in cleaned.columns:
        cleaned["is_target_candidate"] = True
    for col in cleaned.columns:
        if col in text_cols:
            cleaned[col] = cleaned[col].astype(str).str.strip()
        elif col == "is_target_candidate":
            cleaned[col] = cleaned[col].apply(
                lambda value: str(value).strip().lower() in {"true", "1", "yes", "y"}
            )
        else:
            cleaned[col] = pd.to_numeric(cleaned[col], errors="coerce")

    if "date_of_birth" in cleaned.columns:
        cleaned["age"] = calculate_age_as_of(cleaned["date_of_birth"], AS_OF_DATE)

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    return cleaned


def apply_may_2026_context(df: pd.DataFrame) -> pd.DataFrame:
    """Overlay latest checked May 2026 player context on the fallback sample."""

    out = df.copy()
    for player, context in PLAYER_CONTEXT_MAY_2026.items():
        mask = (
            out["player"].eq(player)
            if "player" in out.columns
            else pd.Series(False, index=out.index)
        )
        for column, value in context.items():
            if column not in out.columns:
                out[column] = pd.NA
            out.loc[mask, column] = value
    return out


def calculate_age_as_of(date_of_birth: pd.Series, as_of_date: str) -> pd.Series:
    """Calculate integer football age from date of birth at the project as-of date."""

    dob = pd.to_datetime(date_of_birth, errors="coerce")
    as_of = pd.Timestamp(as_of_date)
    age = as_of.year - dob.dt.year
    has_not_had_birthday = (as_of.month < dob.dt.month) | (
        (as_of.month == dob.dt.month) & (as_of.day < dob.dt.day)
    )
    return (age - has_not_had_birthday.astype(int)).astype("Int64")
